### PR TITLE
Add split-domain option.

### PR DESCRIPTION
**Pull request by rkaminsk**
Add an option to split all domains of incomplete variables on total assignments. I have no clue if this helps or not...

### CODE REVIEW

**Comment by MaxOstrowski** [comment]
Doesn't make a difference in the benchmarks, but why not ...

**Comment by rkaminsk** [comment]
> Doesn't make a difference in the benchmarks, but why not ...

You benchmarked with translation enabled. This option should have no effect if there are no constraints. It should be enabled when translation is disabled.

**Comment by MaxOstrowski** [comment]
There are new results in issue #38 that disable translation for the features.

**Comment by rkaminsk** [comment]
I know and already commented. I just decided to keep this because I also put it in the C++ version. It does not make the code complicated anyway. Maybe there will also be cases where this has an effect. In some of my random tests, there was not difference between the two options because no domains where split.

**Comment by MaxOstrowski** [comment]
I would also recommend to have it in, the question is why to keep this issue open...

**Pull request merged**
