### PR TITLE
started translate minimize

### PR DESCRIPTION
**Pull request by MaxOstrowski**
Task: Translate mininmize constraints to boolean objective function

Do not merge.

@rkaminsk 
Should I create a MinimizeState derived from ConstraintState and override the translate method?
And in case that translation is enabled add it to the master such that it can be translated during the master.translate call in Propagator.init ?

### CODE REVIEW

**Comment by rkaminsk** [comment]
> Should I create a MinimizeState derived from ConstraintState and override the translate method?

Overriding implementations is never a good idea (except to replace a default implementation with something better). Best create two constraint states and implement their methods. They can still share the same propagation algorithm.

> And in case that translation is enabled add it to the master such that it can be translated during the master.translate call in Propagator.init ?

Sounds like the right place to do this.

**Comment by MaxOstrowski** [comment]
> Overriding implementations is never a good idea (except to replace a default implementation with something better). Best create two constraint states and implement their methods. They can still share the same propagation algorithm.

As I do not want to have a copy of the propagate/undo/update etc.. code, how would I share this code in python if not using inheritance.
MinimizeState could "own" a ConstraintState as a member, but as State register/attach this could be messy ?

**Comment by rkaminsk** [comment]
There are multiple options. You could move the code into free standing functions or to another object. You could also implement common functionality in a shared abstract base class and implement then specializations in derived classes. When inheriting keep in mind to *specialize* and not replace with something completely different.

**Comment by MaxOstrowski** [comment]
I tried "something".
There is still a unit test failing, as I do not know how to fully get rid of the minimize statement.
I had to add it to the constraints to be automatically translated, after translation it is removed from the list of constraints (ll 900, but without using the remove_constraint function) but it still persists in the master._todo list.
This results in a failure when copying the state at the end of init.

**Comment by rkaminsk** [comment]
> I tried "something".
> There is still a unit test failing, as I do not know how to fully get rid of the minimize statement.
> I had to add it to the constraints to be automatically translated, after translation it is removed from the list of constraints (ll 900, but without using the remove_constraint function) but it still persists in the master._todo list.
> This results in a failure when copying the state at the end of init.

Then `remove_constraint` also has to remove it from the todo list? We also have to be careful to properly handle it in the propagator, which keeps a reference to it around. Furthermore, we also have to be careful in the multi-shot case. If one minimize-constraint has been translated, all future minimize constraints have to be translated too. Otherwise, it will just break.

**Comment by rkaminsk** [comment]
I did a bit of cleanup and fixed the tests. We still need more tests! I would like to see something like `csp.tests.test_csp.TestMain.test_optimize_bound` for the case that minimize constraints are translated. For this, we might have to adjust the test solver a bit so that it can better deal with translated minimize constraints. Also, we should make sure that once a minimize constraint has been translated all future minimize constraints will be translated too. Maybe with an additional flag in the propagator.

**Comment by rkaminsk** [comment]
I implemented the points mentioned above. The only thing left that still comes to my mind is multi-criteria optimization with priorities. But this is (a little) more complicated to implement and I would rather not do it until we have an application where we actually need this. Please have a look.

**Comment by MaxOstrowski** [comment]
Looks good. Maybe adding another test where we switch from manual optimization to translated optimization ?

**Pull request merged**
