### PR TITLE
Feature/multiset

### PR DESCRIPTION
**Pull request by rkaminsk**
Treat terms in theory atoms as multisets.

### CODE REVIEW

**Comment by MaxOstrowski** [comment]
Are you sure that this is what clingcon wants ?
```
&sum{x;x} = 2.
&show{x}.  
```
results in x=2 in clingcon-3.3.0 version.
I do not completely object the multiset thing but ew would have to consider examples to see what is intuituve. Especially i would need to be consistent, as:
```
&sum{a(2); a(1+1)} = 6.
```
could be treated as `2*a(2)` currently.

**Comment by rkaminsk** [comment]
> Are you sure that this is what clingcon wants ?

No. :smile: In the end, I also think that all this is not terribly important. It is just about getting consistent handling of corner cases.

> ```
> &sum{x;x} = 2.
> &show{x}.  
> ```
> 
> results in x=2 in clingcon-3.3.0 version.
> I do not completely object the multiset thing but ew would have to consider examples to see what is intuituve.

Right now we support terms in sum constraints. With sets of terms one always has to make a decision what to do with things like `x+1`, `1+x`, `x+0`, `x`, etc. The multiset patch avoids this.

> ```
> &sum{a(2); a(1+1)} = 6.
> ```
> 
> could be treated as `2*a(2)` currently.

It was treated as `2*a(2)` before and is now. What is different is that `&sum{a(2); a(2)} = 6` is also treated like `2*a(2)` now.

We do not have to apply this patch. Another option could also be to allow the user to add conditions himself. Say, to allow writing `&sum{x,1;x,2} = 2` to get `x=4`. One could also restrict terms in sum constraints to variables. Then, sets are simple and intuitive.

**Comment by MaxOstrowski** [comment]
I think you are right that these should be multisets. Although it has some drawbacks.
Agreed with merging.

**Comment by rkaminsk** [comment]
I am just going to merge this. It is also not something that is difficult to change later, should we decide to, because it is completely handled in the parsing frontend.

**Pull request merged**
